### ISSUE TITLE
Xcode archiving fails with Undefined Symbol error

### ISSUE THREAD

**Issue by FloPMT** [Kirpal/smart_reply#1]
Hi @Kirpal, first of all thank you for providing this package!

I've just successfully implemented everything and successfully tested it on the iOS simulator. When I try to archive the project however, I get the following errors:
`Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MLKSmartReplySuggestion", referenced from:
      objc-class-ref in smart_reply(SwiftSmartReplyPlugin.o)
  "_OBJC_CLASS_$_MLKTextMessage", referenced from:
      objc-class-ref in smart_reply(SwiftSmartReplyPlugin.o)
  "_OBJC_CLASS_$_MLKSmartReply", referenced from:
      objc-class-ref in smart_reply(SwiftSmartReplyPlugin.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

These are my specs:
Xcode 12.3
Deployment target iOS 10

**Comment by FloPMT** [comment]
Hi @Kirpal, I just checked and confirmed that this also happens in the provided example project so you should be able to replicate it.

**Comment by FloPMT** [comment]
Hi @Kirpal, I found the issue. MLKit only works for 64 bit devices on iOS. Thus using either the latest iOS 14 deployment targets or manually limiting the project to use 64 bit solves the issue:
https://stackoverflow.com/questions/33646553/ios-limit-app-to-64-bit-devices-only

**Comment by Kirpal** [comment]
Thank you! I updated the readme to clarify.
